package io.github.vasilyrylov.archsample.common.ui.theme

import androidx.compose.ui.graphics.Color

// Colors from "Theming in Compose with Material 3" codelab
// https://codelabs.developers.google.com/jetpack-compose-theming#0

internal val md_theme_light_primary = Color(0xFF825500)
internal val md_theme_light_onPrimary = Color(0xFFFFFFFF)
internal val md_theme_light_primaryContainer = Color(0xFFFFDDB3)
internal val md_theme_light_onPrimaryContainer = Color(0xFF291800)
internal val md_theme_light_secondary = Color(0xFF6F5B40)
internal val md_theme_light_onSecondary = Color(0xFFFFFFFF)
internal val md_theme_light_secondaryContainer = Color(0xFFFBDEBC)
internal val md_theme_light_onSecondaryContainer = Color(0xFF271904)
internal val md_theme_light_tertiary = Color(0xFF51643F)
internal val md_theme_light_onTertiary = Color(0xFFFFFFFF)
internal val md_theme_light_tertiaryContainer = Color(0xFFD4EABB)
internal val md_theme_light_onTertiaryContainer = Color(0xFF102004)
internal val md_theme_light_error = Color(0xFFBA1A1A)
internal val md_theme_light_errorContainer = Color(0xFFFFDAD6)
internal val md_theme_light_onError = Color(0xFFFFFFFF)
internal val md_theme_light_onErrorContainer = Color(0xFF410002)
internal val md_theme_light_background = Color(0xFFFFFBFF)
internal val md_theme_light_onBackground = Color(0xFF1F1B16)
internal val md_theme_light_surface = Color(0xFFFFFBFF)
internal val md_theme_light_onSurface = Color(0xFF1F1B16)
internal val md_theme_light_surfaceVariant = Color(0xFFF0E0CF)
internal val md_theme_light_onSurfaceVariant = Color(0xFF4F4539)
internal val md_theme_light_outline = Color(0xFF817567)
internal val md_theme_light_inverseOnSurface = Color(0xFFF9EFE7)
internal val md_theme_light_inverseSurface = Color(0xFF34302A)
internal val md_theme_light_inversePrimary = Color(0xFFFFB951)
internal val md_theme_light_shadow = Color(0xFF000000)
internal val md_theme_light_surfaceTint = Color(0xFF825500)
internal val md_theme_light_outlineVariant = Color(0xFFD3C4B4)
internal val md_theme_light_scrim = Color(0xFF000000)

internal val md_theme_dark_primary = Color(0xFFFFB951)
internal val md_theme_dark_onPrimary = Color(0xFF452B00)
internal val md_theme_dark_primaryContainer = Color(0xFF633F00)
internal val md_theme_dark_onPrimaryContainer = Color(0xFFFFDDB3)
internal val md_theme_dark_secondary = Color(0xFFDDC2A1)
internal val md_theme_dark_onSecondary = Color(0xFF3E2D16)
internal val md_theme_dark_secondaryContainer = Color(0xFF56442A)
internal val md_theme_dark_onSecondaryContainer = Color(0xFFFBDEBC)
internal val md_theme_dark_tertiary = Color(0xFFB8CEA1)
internal val md_theme_dark_onTertiary = Color(0xFF243515)
internal val md_theme_dark_tertiaryContainer = Color(0xFF3A4C2A)
internal val md_theme_dark_onTertiaryContainer = Color(0xFFD4EABB)
internal val md_theme_dark_error = Color(0xFFFFB4AB)
internal val md_theme_dark_errorContainer = Color(0xFF93000A)
internal val md_theme_dark_onError = Color(0xFF690005)
internal val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
internal val md_theme_dark_background = Color(0xFF1F1B16)
internal val md_theme_dark_onBackground = Color(0xFFEAE1D9)
internal val md_theme_dark_surface = Color(0xFF1F1B16)
internal val md_theme_dark_onSurface = Color(0xFFEAE1D9)
internal val md_theme_dark_surfaceVariant = Color(0xFF4F4539)
internal val md_theme_dark_onSurfaceVariant = Color(0xFFD3C4B4)
internal val md_theme_dark_outline = Color(0xFF9C8F80)
internal val md_theme_dark_inverseOnSurface = Color(0xFF1F1B16)
internal val md_theme_dark_inverseSurface = Color(0xFFEAE1D9)
internal val md_theme_dark_inversePrimary = Color(0xFF825500)
internal val md_theme_dark_shadow = Color(0xFF000000)
internal val md_theme_dark_surfaceTint = Color(0xFFFFB951)
internal val md_theme_dark_outlineVariant = Color(0xFF4F4539)
internal val md_theme_dark_scrim = Color(0xFF000000)
